model:
  name: "gnn_md"
  target: "adaptability"
  hidden_dim: 128
  num_layers: 5
  gnn_md_attention_heads: 4

data:
  frame_strategy: "frame_zero"

train:
  run_name: "ablation_arch_target_gnn_md_adapt"
  seed: 42
